### PR TITLE
Fix deed form

### LINKED ISSUE #187: Add form for deed to dashboard

### PR DESCRIPTION
**Pull request by crawfoal**
## Description
This PR moves the deed form to the dashboard and adds animation to make it obvious that the pictures are uploading.

Fixes #187 

## Developer Checklist
- [ ] I have read and followed the [contribution guidelines](
      https://github.com/crawfoal/greensteps/blob/master/CONTRIBUTING.md).
- [ ] All specs and linters pass, including Code Climate and Semaphore
- [ ] I have followed the style and design of nearby code (e.g. you added
      a new controller action and it matches the style and design of other
      actions in that same controller)
- [ ] My changes have reasonable test coverage
- [ ] I have gone through my changes by hand, either in the browser or
      terminal, which ever makes sense
- [ ] I have all user facing strings are internationalized

## Reviewer Checklist
- [ ] All specs and linters pass, includeing Code Climate and Semaphore
- [ ] The changes follow the style and design of nearby code or similar
      code within this project (e.g. this PR adds a new controller action 
      and it matches the style and design of other actions in that same 
      controller)
- [ ] The changes have reasonable test coverage
- [ ] I have gone through the changes by hand, either in the browser or
      terminal, which ever makes sense
- [ ] I have all user facing strings are internationalized

### CODE REVIEW

File: app/models/deed.rb [hunk 1]
```diff
@@ -9,7 +9,7 @@ class Deed < ApplicationRecord
   scope :total_trash_bags, -> { sum(:trash_bags) }
 
   def photos_are_attached
-    errors.add(:before_photo, :required) unless before_photo.attached?
+    # errors.add(:before_photo, :required) unless before_photo.attached?
```
Comment (Atul9) [inline app/models/deed.rb]: Can we delete this line?
